### PR TITLE
Dark-light toggle button is fixed

### PR DESCRIPTION
**Pull request by vandana3869**
issue #117 is fixed
Screenshot 2022-10-16 003159
Screenshot 2022-10-16 003115

### CODE REVIEW

**Comment by vandana3869** [comment]
@vishaaal could you please review this PR

**Comment by vishaaal** [comment]
Few fonts should turn white for dark mode @vandana3869

**Comment by vandana3869** [comment]
fixed
image
image

**Comment by vandana3869** [comment]
@vishaaal  could you please review this PR

**Pull request merged**
