### PR TITLE
Modifing the responsiveness of Jumbo header Book Case for Small devices

### PR DESCRIPTION
**Pull request by Saikatssd**
@vishaaal Please merge this pull request.
This problem aligns with #131.

### CODE REVIEW

**Comment by vishaaal** [comment]
Please attach a screenshot

**Comment by Saikatssd** [comment]
@vishaaal  Please check this.

**Comment by vishaaal** [comment]
Great job! Can you make the footer responsive too @Saikatssd

**Comment by Saikatssd** [comment]
@vishaaal yes I can and I have attached the screenshot in issue #95. Please assign me

**Comment by Saikatssd** [comment]
@vishaaal Please check this.

**Pull request merged**
