### PR TITLE
add search bar and my favourite book

### PR DESCRIPTION
**Pull request by Sourabh06**
The search bar
search bar

positive search response
positive search

negative search response
negative search

### CODE REVIEW

**Comment by vishaaal** [comment]
Would be great if it only shows the book listed while hiding others while searching

**Comment by Sourabh06** [comment]
added the filter functionality
filter


filter2

**Comment by Sourabh06** [comment]
merged to latest commit :)

**Comment by vishaaal** [comment]
Great job @Sourabh06 ✨🎉

**Pull request merged**
