### PR TITLE
fix the search bar width

### PR DESCRIPTION
**Pull request by GarvLuthra24**
Fix issue #113 increased the search bar width to make it more user friendly

@vishaaal please review my pull request and add the hacktoberfest label

Screenshot 2022-10-14 at 10 13 18 PM

### CODE REVIEW

**Comment by vishaaal** [comment]
Please add a screenshot @GarvLuthra24

**Comment by GarvLuthra24** [comment]
> @vishaaal 
Screenshot from 2022-10-14 20-39-48

**Comment by GarvLuthra24** [comment]
@vishaaal please review my pull request and add hacktoberfest-accepted label to it

**Comment by GarvLuthra24** [comment]
@vishaaal   thanks for the merge. Can you please add the hactoberfest-accepted label to this commit

**Pull request merged**
