### PR TITLE
Updated Footer by adding social sites and navigations

### PR DESCRIPTION
**Pull request by Abhinav-3359**
please merge this under hacktoberfest.

### CODE REVIEW

**Comment by vishaaal** [comment]
@Abhinav-3359 send a screenshot of the functionality you have added

**Comment by Abhinav-3359** [comment]
image

**Comment by vishaaal** [comment]
Only two social icons - 
1. Github
2. LinkedIn
year will  be 2022
@Abhinav-3359

**Comment by Abhinav-3359** [comment]
Sir pls review

**Comment by Abhinav-3359** [comment]
Sir please specify the reason

**Pull request closed without merging**
